name: lab

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run-lab:
    runs-on: ubuntu-latest
    steps:
      - name: Executa shell
        run: |
          apt update && apt install -y git python3-git
          echo "Ola mundo !"
          echo "::notice::Ola mundo, estou vivo"
