name: lab

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run-lab:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Executa shell
        run: |
          sudo apt update && sudo apt install -y git python3-git
          echo "Ola mundo !"
          echo "::notice::Ola mundo, estou vivo"
